[package]
name = "mp4combine"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
jni = { version = "^0.19.0", optional = true }

[features]
default = []
clib = []
